import test from 'node:test';import assert from 'node:assert/strict';import * as M from '../dist/model.js';
test('sample totals and market ownership match the approved final screens',()=>{const s=M.seed();assert.equal(M.total(s.bills.flatMap(b=>b.items)),416.5);assert.equal(M.total(s.bills.filter(b=>b.marketId==='vidya').flatMap(b=>b.items)),280.5);});
test('quantity edits, suggested rates and removal produce the approved 93 bill',()=>{const s=M.seed();M.selectMarket(s,'vidya');const t=M.commitLine(s,{productId:'tomato',qty:2.5,rate:25});const c=M.commitLine(s,{productId:'coriander',qty:2,rate:12});assert.equal(M.total(s.draft.items),86.5);M.commitLine(s,{...t,qty:3});M.removeLine(s,c.id);M.commitLine(s,{productId:'potato',qty:1,rate:18});assert.equal(M.total(s.draft.items),93);});
test('pending editor values never enter totals and saved snapshots are immutable',()=>{const s=M.draftScenario();s.editor={productId:'tomato',qty:90,rate:99};const req=M.beginSave(s);const saved=M.finishSave(s,req.id);assert.equal(M.total(saved.items),93);M.nextBill(s);M.commitLine(s,{productId:'tomato',qty:1,rate:8});assert.equal(M.total(saved.items),93);assert.equal(s.bills.length,4);});
test('save failure retry and unknown outcome reconciliation never duplicate a bill',()=>{const s=M.draftScenario();const req=M.beginSave(s);M.saveOutcome(s,'failed');assert.equal(M.beginSave(s).id,req.id);M.saveOutcome(s,'unknown');assert.throws(()=>M.removeLine(s,s.draft.items[0].id));const restored=JSON.parse(JSON.stringify(s));const a=M.finishSave(restored,req.id);const b=M.finishSave(restored,req.id);assert.equal(a.id,b.id);assert.equal(restored.bills.length,4);assert.equal(restored.draft,null);});
test('receipt retries never change saved financial data or bill count',()=>{const s=M.draftScenario();const b=M.finishSave(s,M.beginSave(s).id);M.sendReceipt(s,b.id);M.receiptOutcome(s,b.id,'failed');assert.equal(b.receipt,'failed');M.sendReceipt(s,b.id);M.receiptOutcome(s,b.id,'sent');assert.equal(b.receipt,'sent');assert.equal(M.total(b.items),93);assert.equal(s.bills.length,4);});
test('switching market requires explicit discard; same market preserves draft',()=>{const s=M.draftScenario();M.selectMarket(s,'vidya');assert.equal(M.total(s.draft.items),93);assert.throws(()=>M.selectMarket(s,'gangapur'));M.selectMarket(s,'gangapur',true);assert.equal(s.draft.items.length,0);assert.equal(s.bills.length,3);assert.throws(()=>M.selectMarket(s,'mandai',true));});
test('validation rejects invalid count, rate, quantity and contact',()=>{const s=M.seed();M.selectMarket(s,'vidya');for(const entry of [{productId:'coriander',qty:1.5,rate:12},{productId:'tomato',qty:0,rate:25},{productId:'tomato',qty:2,rate:-1},{productId:'tomato',qty:2,rate:'1.999'}])assert.throws(()=>M.commitLine(s,entry));assert.equal(s.draft.items.length,0);assert.throws(()=>M.setPhone(s,'123'));assert.equal(M.setPhone(s,'+91 98765 43210'),'9876543210');});
test('no-contact save is valid and cannot send a receipt',()=>{const s=M.draftScenario();M.setPhone(s,'');const b=M.finishSave(s,M.beginSave(s).id);assert.equal(b.receipt,'not_requested');assert.throws(()=>M.sendReceipt(s,b.id));});
